name: GoLang to GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.14.1'

      name: lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangco-lint/master/install.
        sh | sh -s -- -b $(go enc GOPATH)/bin v1.26.0

        golangci-list run
